# Generated by Django 4.0.3 on 2022-03-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='unit',
            field=models.ForeignKey(default='29bc80d8-2b89-47ed-9f39-9943fcefa98a', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='unit.units', verbose_name='Единица измерения'),
        ),
    ]
