# Generated by Django 4.0.3 on 2022-03-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_prices_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='unit',
        ),
    ]
