# Generated by Django 4.0.3 on 2022-03-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
        ('price', '0006_remove_prices_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='unit.units', verbose_name='Единица измерения'),
            preserve_default=False,
        ),
    ]
