# Generated by Django 4.0.3 on 2022-03-21 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_prices_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
