# Generated by Django 4.0.3 on 2022-03-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_alter_prices_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
