# Generated by Django 4.0.3 on 2022-03-15 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('UnitName', models.CharField(blank=True, max_length=20, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Ед.изм.',
                'verbose_name_plural': 'Ед.изм.',
            },
        ),
    ]
